# Generated by Django 5.0.7 on 2026-06-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
    ]
